import { FooterComponent } from '@/components/FooterComponent'
import './globals.css'
import { HeaderComponent } from '@/components/HeaderComponent'
import 'bootstrap/dist/css/bootstrap.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
        <HeaderComponent />
        <main className='app'>
          {children}
        </main>
        
        <FooterComponent />
      </body>
      
    </html>
  )
}
